### ISSUE TITLE
The iPad version no longer works at all. (iPad Pro (12.9 inch, 4th generation)

### ISSUE THREAD

**Issue by 00SilentStorm00** [imxieyi/waifu2x-ios#71] opened 2023-06-23 06:37 UTC
![image](https://github.com/imxieyi/waifu2x-ios/assets/117681325/3eaaae8e-64c0-4ac7-8e0c-5197175c3747)

**Comment by imxieyi** [comment] 2023-06-23 17:00
This is due to iOS 17 beta changing data format from Core ML. The issue is being investigated. Only Real-CUGAN models have this issue so please use other models until the issue is fixed (soon-ish).

**Comment by imxieyi** [comment] 2023-06-24 11:19
The problem is fixed in the latest version (7.2.2). Feel free to update and reopen if it's still not working.

**Closed as completed by imxieyi** 2023-06-24 11:19 UTC
