### ISSUE TITLE
cannot use CUGAN model on iOS17

### ISSUE THREAD

**Issue by Tobybox** [imxieyi/waifu2x-ios#72] opened 2023-06-23 13:35 UTC

**Comment by imxieyi** [comment] 2023-06-23 16:58
I already noticed this issue. Looks like iOS 17 changed the array memory layout which the app made assumptions on. Don't know if Apple will revert this change but it can be solved from the app.

**Comment by Tobybox** [comment] 2023-06-24 01:24
Thank you for your work☺️

Yi Xie ***@***.***>于2023年6月24日 周六00:58写道：

**Comment by imxieyi** [comment] 2023-06-24 11:19
The problem is fixed in the latest version (7.2.2). Feel free to update and reopen if it's still not working.

**Closed as completed by imxieyi** 2023-06-24 11:19 UTC
