### ISSUE TITLE
Issues with Ventura 13.0.1 with command line usage

### ISSUE THREAD

**Issue by nihelmasell** [imxieyi/waifu2x-ios#59] opened 2022-11-20 13:17 UTC
Hi, I recently updated my Mac to the latest version of macOS. I have been using your software from the command line without any issues. Now the software hangs with the first image. I purchased your app via App Store. I also re-added the input and output folders to the app, and tried uninstalling and reinstalling the app. Also tried with different types of images. The weird thing is the same happens with realesrgan-ncnn-vulkan , both with the binary and the python installation. I cannot really guess what's happening. The hardware is the same. And there were no major changes in Ventura. Best regards.

**Comment by imxieyi** [comment] 2022-11-20 14:45
This is the same as #57.
Are you using Intel-based Mac? ARM-based Mac doesn't seem to suffer from this issue since the Neural Engine is used.

**Comment by nihelmasell** [comment] 2022-11-21 13:47
> This is the same as #57.
> Are you using Intel-based Mac? ARM-based Mac doesn't seem to suffer from this issue since the Neural Engine is used.

No, I am using M1 PRO Mac.

**Comment by imxieyi** [comment] 2022-11-21 17:02
That's strange. Can you please run the following command in Terminal app while it hangs?
```bash
killall -segv waifu2x
```
Then macOS should show a crash report. Please copy the full content and share it. If you don't want to share publicly please send it via email to support@waifu2x.app.

**Comment by nihelmasell** [comment] 2022-11-24 20:41
> That's strange. Can you please run the following command in Terminal app while it hangs?
> 
> ```shell
> killall -segv waifu2x
> ```
> 
> Then macOS should show a crash report. Please copy the full content and share it. If you don't want to share publicly please send it via email to [support@waifu2x.app](mailto:support@waifu2x.app).

Hi, I tried what you suggested, but it remains halted, it doesn't dump any crash report.

**Comment by imxieyi** [comment] 2022-11-29 10:34
That's strange. Did the app exit with non-zero exit code when you killed it?

**Comment by nihelmasell** [comment] 2022-12-01 00:24
> That's strange. Did the app exit with non-zero exit code when you killed it?

It remained unresponsive, even when sending kill signals. But it started writing the first image, with zero bytes in. 

I don't know if the app was updated, but now I'm getting the "Please purchase additional models for Mac in the app" message. So now it doesn't even start. I bought models for both iOS and the MacOS. It's a MacBookPro18,3 btw.

**Comment by imxieyi** [comment] 2022-12-01 12:24
That's strange. Did you sign out your Apple ID? If not please open the app and see if it's lost in the app as well.

**Comment by nihelmasell** [comment] 2022-12-01 17:21
> That's strange. Did you sign out your Apple ID? If not please open the app and see if it's lost in the app as well.

I haven't signed out of my Apple ID. Within the app, the process works fine, even with the premium models.

**Comment by imxieyi** [comment] 2022-12-02 11:03
Thanks for the info! It's a regression on macOS 13. If GUI works fine then the fix in the recent update is working. The next version will include that fix in CLI as well.

**Comment by imxieyi** [comment] 2022-12-14 10:23
The issue with purchase verification in CLI should be fixed in the latest version (6.2.6). Feel free to update. The hang issue is unfortunately not reproducable on my devices. I haven't figured out a way to debug it without reproducing locally. As soon as it reproduces on my side I'll start investigation.

**Comment by nihelmasell** [comment] 2022-12-19 06:21
> The issue with purchase verification in CLI should be fixed in the latest version (6.2.6). Feel free to update. The hang issue is unfortunately not reproducable on my devices. I haven't figured out a way to debug it without reproducing locally. As soon as it reproduces on my side I'll start investigation.

The issue with purchase verification in CLI was solved.

The remaining issue persisted, till I updated to macOS 13.1 today. Just in case someone has the same OS (macOS 13.0) and the same model (MKGT3LL/A).

**Comment by nihelmasell** [comment] 2022-12-24 14:36
> The issue with purchase verification in CLI should be fixed in the latest version (6.2.6). Feel free to update. The hang issue is unfortunately not reproducable on my devices. I haven't figured out a way to debug it without reproducing locally. As soon as it reproduces on my side I'll start investigation.

Hi, I have to sadly write to you again. I have read the other thread you quoted me into, and, disgracefully, it happened to me the same described there (newly). I tested with a folder a couple days ago: it worked perfectly. The machine was kept open, no reboot, nothing was changed. Just opened Topaz G. AI and edited a couple pictures there. I noticed the preview was slow, much slower than before. But then the processing of the photos was normal. I think yesterday I have retried processing a bunch of pictures and your program went to halt again. This is something I just can't explain. I saw it working before yesterday, I even have the bunch of upscaled pictures. I made a batch script to resize video files, as your script didn't work correctly. And the GUI couldn't process 720p to 5k video. So I have a bunch of 15000 frames to be processed. I don't think the App can handle that, and even then, I would have to mix it with a bash or zsh script to add the audio and make the movie.

**Comment by imxieyi** [comment] 2022-12-24 15:12
That's strange. I tried many times on my M1 Mac on 13.0 but it just refused to reproduce the issue.

Did you try to reboot your Mac when it hang?

**Comment by imxieyi** [comment] 2022-12-26 13:43
I have an idea of what could be happening here (assuming that you have problem with only CLI, not GUI). I have implemented a very hacky workaround and there is a slight chance it would fix the problem (in a super ugly way). If you are interested in trying it please send your Apple ID to feedback@waifu2x.app and I'll invite you to a TestFlight build.

As for video processing. The script I provided is just an example of what's possible. You will need to adjust the parameters  accordingly to fit your need. I'd suggest that you read some tutorials about how to use ffmpeg to understand what each argument means.

**Comment by imxieyi** [comment] 2023-01-10 11:30
The latest update (6.2.7) is supposed to solve this. Just add `--stub-ui` flag and it should no longer be stuck. Feel free to reopen if you are still having issues.

**Closed as completed by imxieyi** 2023-01-10 11:30 UTC
